apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nextcloud-secret
  namespace: nextcloud
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore

  target:
    name: nextcloud-secret
    creationPolicy: Owner
    
  dataFrom:
  - extract:
      key: nextcloud-secret