apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextcloud
  template:
    metadata:
      labels:
        app: nextcloud
    spec:
      containers:
        - name: nextcloud
          image: nextcloud:33
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: MYSQL_HOST
              value: nextdb
            - name: MYSQL_DATABASE
              value: nextcloud
            - name: REDIS_HOST
              value: redis
            - name: NEXTCLOUD_TRUSTED_DOMAINS
              value: nextcloud.aboft.dev
            - name: OVERWRITEHOST
              value: nextcloud.aboft.dev
            - name: OVERWRITEPROTOCOL
              value: https
            - name: TRUSTED_PROXIES
              value: 10.42.0.0/16
          envFrom:
            - secretRef:
                name: nextcloud-secret
          volumeMounts:
            # - name: nextcloud-pvc
            #   mountPath: /var/www/html
            #   subPath: html
            - name: nextcloud-pvc
              mountPath: /var/www/html/custom_apps
              subPath: custom_apps
            - name: nextcloud-pvc
              mountPath: /var/www/html/config
              subPath: config
            - name: nextcloud-pvc
              mountPath: /var/www/html/data
              subPath: data
      volumes:
        - name: nextcloud-pvc
          persistentVolumeClaim:
            claimName: nextcloud-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: nextcloud
spec:
  selector:
    app: nextcloud
  ports:
    - port: 80
      targetPort: 80