apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: aboftybot-secret
  namespace: aboftybot
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore

  target:
    name: aboftybot-secret

  dataFrom:
    - extract:
        key: aboftybot