apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: auth-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: auth-secret
  dataFrom:
    - extract:
        key: "op://k3s-homelab/auth-secret"