apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: aerospike-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: aerospike-secret
    deletionPolicy: Retain
  data:
    - secretKey: features.conf
      remoteRef:
        key: aerospike-secret/features.conf
