apiVersion: v1
data:
  basics.lua: |
    function getDeviceSize(rec)
      return record.device_size(rec)
    end
    function getSetName(rec)
      return record.setname(rec)
    end
    function delete_record(rec)
      -- Attempt to delete the record
      local status = aerospike:remove(rec)
      if status ~= 0 then
          -- Log only if there is an error in deletion
          info("Failed to delete record: %s. Error Code: %d", record.digest(rec), status)
      end
      return status
    end
  example.lua: |
    local function one(rec)
      return 1
    end

    local function add(a, b)
      return a + b
    end

    function count(stream)
      return stream : map(one) : reduce(add);
    end
kind: ConfigMap
metadata:
  name: udfs