# platform/observability/externals/scrapeconfig-aerospike-node-exporters.yaml
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: aerospike-exporters
  namespace: monitoring
  labels:
    prometheus: kps
spec:
  kubernetesSDConfigs:
    - role: Pod
      namespaces:
        names:
          - asdb-prod
          - asdb-staging

  relabelings:
    - sourceLabels:
        - __meta_kubernetes_pod_container_name
      regex: aerospike-prometheus-exporter
      action: keep

    - sourceLabels:
        - __meta_kubernetes_pod_ip
      targetLabel: __address__
      replacement: $1:9145

    - sourceLabels:
        - __meta_kubernetes_namespace
      targetLabel: namespace

    - sourceLabels:
        - __meta_kubernetes_pod_name
      targetLabel: pod
