apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: homelab-static
  namespace: metallb-system
spec:
  addresses:
    - 192.168.88.10/32
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: homelab-static
  namespace: metallb-system
spec:
  ipAddressPools:
    - homelab-static