apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: exporter-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: exporter-secret
  dataFrom:
    - extract:
        key: exporter-secret