# argocd/apps/aboftybot-prod.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aboftybot
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/aboft/aboftybot-go.git
    targetRevision: main
    path: deploy/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: aboftybot
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true