# argocd/apps/aboftybot-staging.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aboftybot-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/aboft/homelab-gitops.git
    targetRevision: main
    path: apps/aboftybot/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: aboftybot-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true