apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aerospike-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/aboft/homelab-gitops.git
    targetRevision: main
    path: platform/aerospike/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: asdb-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true